# Generated by Django 6.0.7 on 2026-07-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=255)),
                ('allowed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('conditional', 'Conditional')], max_length=50)),
                ('condition', models.TextField()),
                ('fallback_behavior', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
                ('tone', models.CharField(max_length=100)),
                ('example_response', models.TextField()),
                ('do_rules', models.TextField()),
                ('dont_rules', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('context', models.TextField()),
                ('ideal_answer', models.TextField()),
                ('category', models.CharField(choices=[('pricing', 'Pricing'), ('acquisition', 'Acquisition'), ('negotiation', 'Negotiation'), ('risk', 'Risk'), ('strategy', 'Strategy'), ('legal', 'Legal')], max_length=50)),
                ('authority_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('forbidden', 'Forbidden')], max_length=20)),
                ('action_type', models.CharField(choices=[('buy', 'Buy'), ('reject', 'Reject'), ('negotiate', 'Negotiate'), ('escalate', 'Escalate'), ('delay', 'Delay'), ('conditional', 'Conditional')], max_length=50)),
                ('reasoning', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlaggedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('flag_reason', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_answer', models.TextField(blank=True, null=True)),
                ('converted_to', models.CharField(blank=True, max_length=50, null=True)),
                ('converted_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='core_conver_session_e73757_idx')],
            },
        ),
    ]
